services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    environment:
      - PUID=${PUID-1000}
      - PGID=${PGID-1000}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHED_URL} #optional
    volumes:
      - jellyfin_config:/config
      - ${MOVIES_SOURCE_PATH}:/data/movies
      - ${TV_SHOWS_SOURCE_PATH}:/data/tvshows
    ports:
      - 8096:8096
      - 8920:8920 # Optional - Https webUI (you need to set up your own certificate).
      - 7359:7359/udp # Optional - Allows clients to discover Jellyfin on the local network.
      - 1900:1900/udp # Optional - Service discovery used by DNLA and clients.
    restart: unless-stopped
    networks:
      - default

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    hostname: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - jellyseerr_config:/app/config
    restart: unless-stopped
    networks:
      - default

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    environment:
      - PUID=${PUID-1000}
      - PGID=${PGID-1000}
      - TZ=${TZ}
    volumes:
      - radarr_config:/config
      - ${DOWNLOADS_SOURCE_PATH}:/downloads
      - ${MOVIES_SOURCE_PATH}:/movies
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - default

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    environment:
      - PUID=${PUID-1000}
      - PGID=${PGID-1000}
      - TZ=${TZ}
    volumes:
      - sonarr_config:/config
      - ${DOWNLOADS_SOURCE_PATH}:/downloads
      - ${TV_SHOWS_SOURCE_PATH}:/tv
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - default

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    hostname: sabnzbd
    environment:
      - PUID=${PUID-1000}
      - PGID=${PGID-1000}
      - TZ=${TZ}
    volumes:
      - sabnzbd_config:/config
      - ${DOWNLOADS_SOURCE_PATH}:/downloads
      - ${DOWNLOADS_SOURCE_PATH}/incomplete:/incomplete-downloads
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - default

volumes:
  jellyfin_config:
  jellyseerr_config:
  radarr_config:
  sonarr_config:
  sabnzbd_config:

networks:
  default:
    name: ${PROXY_NETWORK_NAME}
    external: true
